### ISSUE TITLE
About the new playlist file format (tab-delimited CSV)

### ISSUE THREAD

**Issue by fmaida** [libretro/ludo#152]
Hi. I see that starting from v0.3.5 you've chosen to generate CSV files with tab-separated fields for the playlist. Correct me if I am mistaken, but in the CSV files for each entry you're storing these three information:

1. The path to the file
2. Game name
3. The ID number used to recognize the game in the database

I didn't see a fourth parameter to specify the core to be used to emulate a specific entry, or at least I tried to specify it at the tail of each row but Ludo didn't recognized that.

I was wondering... what would happen if one day you'll decide to implement a "favorites" tab, just like RetroArch where everyone can put their all-time favourite games taken from different systems? 

Because in this case, if I'm not mistaken your file format wouldn't work. Feel free to correct me if I am wrong, but I tried to create manually a "favorites" playlist named `favorites.csv` with three games taken from three different systems (Atari 2600, NES and Sega Megadrive). It resembles this imaginary one:

```csv
/path/to/roms/Atari 2600/Space Invaders (1978) (Atari) [!].a26.zip	Space Invaders (USA)	2800248755
/path/to/roms/Gameboy/Lock 'N' Chase (JU).gb.zip	Lock n' Chase ~ Lock 'n' Chase (World)	3669564538
/path/to/roms/Sega Megadrive/Sonic The Hedgehog (W) (REV01) [!].gen.zip	Sonic The Hedgehog (Japan, Korea)	2950717166
```

When I launch Ludo, it recognizes the playlist and displays it. However when I try to launch a game, I'm getting a `default core not set` error. In the old playlist format you could specify a specific core for each entry in a playlist, however with this format you can't. 

This is just IMHO and you probably already have a better idea about how to manage this issue, but maybe you could add a fourth field in your playlist format where you specify the default core to be used for each entry. Eventually you could also avoid to enter the fourth field or put the value "DETECT" (just like RetroArch) to let Ludo guess would be the most suited emulator core to use.

By adding a fourth field you can also solve another problem:
What happens if a core can emulate properly 99 games out of 100?
Someone could leave the default value for the 99 working games and use another core for the problematic game, for example:

```csv
/path/to/games/Balloon Fight (U) [!].nes.zip	Balloon Fight (USA)	3415201714	DETECT
/path/to/games/Contra (U) [!].nes.zip	Contra (USA)	3305800452	DETECT
/path/to/games/Donkey Kong Classics (U) [!].nes.zip	Donkey Kong Classics (USA, Europe)	401345735	DETECT
/path/to/games/Duck Tales (U) [!].nes.zip	DuckTales (USA)	3703128897	DETECT
/path/to/games/Elevator Action (U) [!].nes.zip	Elevator Action (USA)	3558168351	nestopia_libretro
```

**Comment by kivutar** [comment]
Your remarks are perfectly valid. Ludo wasn't honoring this column anyway, so for now I've removed it.

When the time comes to add History or Favorites I may change the playlist format. But I'm not yet sure how these things should look. For example:

 - in History, I may want to display a date of last played
 - Favorites may simply be pinned entries at the top of each system playlist

There is no requirement to exactly replicate the UI patterns of RetroArch. I may even change what Ludo looks like before v1.0.0.

But there are two thing that won't change: priority goes to stability fixes over everything else, and the code will have to remain small, I'm ready to sacrifice acclaimed features and platforms to achieve these two goals.

**Comment by fmaida** [comment]
I know that this has been suggested before, but what about JSON?
It could allow you to keep a very flexible format and add new necessary fields while developing Ludo, without fearing to break the code that read the playlist.

If I'm not mistaken, maybe you once wrote that JSON is too slow to read ?

Anyway, here's an imaginary playlist file written in JSON:

```json
{
    "title": "Nintendo - Nintendo Entertainment System",
    "defaults": {
        "core_id": "fceumm_libretro",
        "aspect_ratio": "16:10"
    },
    "entries": [
        {
            "id": "3415201714",
            "path": "/path/to/games/Balloon Fight (U) [!].nes.zip",
            "title": "Balloon Fight (USA)",
            "region": "USA",
            "core_id": "nestopia_libretro",
            "last_played": "2019-02-13 08:42:39",
            "pinned": "True"
        },
        {
            "id": "3305800452",
            "path": "/path/to/games/Contra (U) [!].nes.zip",
            "title": "Contra (USA)",
            "pinned": "True"
        },
        {
            "id": "3703128897",
            "path": "/path/to/games/Duck Tales (U) [!].nes.zip",
            "title": "DuckTales (USA)",
            "last_played": "2019-02-11 22:35:16"
        }
    ]
}
```

**Comment by kivutar** [comment]
It's not JSON per se that is too slow. It's just that my scanner code is appending to a playlist file.
Using json there, with the closing `}`, wouldn't support the append mode.

I would have to change the logic of the scanner writer to keep all the playlists in memory, and dump them to the file system only at the end.

It's a tradeoff between using RAM of having a lot of IO.

But since I need to keep all playlists in memory anyway for the deduplication code, I might as well migrate to JSON.

**Comment by i30817** [comment]
Deduplication... I'd like to warn that the RA scanner is fairly simple and doesn't consider games which are softpatched different if their underlying rom is the same. This leads to duplicated (and wrong) entries on the playlist, but that is still 'better' than the hack not even existing.

I'm thinking of changing my 'hack infrastructure' to use a tool that hardpatches roms and simply keeps a revert patch (i already do something very similar with rhdndat, which could be extended to handle that management); but then i'm fairly sure the scanner in the main RA GUIs would just pretend the roms  don't exist if the database doesn't have their entries (which is a problem because both the nes and snes databases are not accepting my more complete PRs).

**Comment by kivutar** [comment]
It's not really surprising that RA doesn't scan ROMs that are patched at launch time. How would you even implement this? Detect the .ups or .ips file with the name name, apply the patch, get the new CRC and match it in the database?

**Comment by i30817** [comment]
my best (and most complicated) idea is to make the scanner - and maybe even the emulators - operate on top of a FUSE filesystem that pretends the game and patch are a single hardpatched file.

This would also finally make the softpatching core independent.

**Comment by i30817** [comment]
Resuming RA needs to do two things to bring sanity to hack playlists:

add a option to always use checksums again instead of serials (serials are not useless because 'fuzzy' ids are sometimes valuable to only have a single configuration etc, but only if they're paired with a higher ranked unique id that can serve as database primary key when necessary).

Goddamn accept big libretro-database PRs for the SNES and NES again.

**Comment by fmaida** [comment]
BTW congratulations on having launched the first version of ludOS. I did not know where to write it because there is not yet a channel dedicated to Ludo on the libretro forum.

**Comment by RobLoach** [comment]
@fmaida Join us on Discord! https://discord.gg/YXYSEQD

**Comment by fmaida** [comment]
Good idea, thanks.
