### ISSUE TITLE
Add option to disable pressing escape to close Ludo

### ISSUE THREAD

**Issue by NovaPhoenix** [libretro/ludo#202]
A lot of people (myself included) accidentally press escape because of muscle memory, and since that instantly causes Ludo to close it can be very painful. It seems very out of place in a user friendly frontend. Please consider adding either a closing dialog or a configuration option to disable this behavior/remap the key. Thanks.

**Comment by brandleesee** [comment]
It has been implemented in Retroarch. Maybe this can be implemented in here as well.

**Comment by kivutar** [comment]
OK I understand the issue.

Now let's try to find the best possible fix, while complying to Ludo design goals.

Please note that ludo doesn't support binding combos like `alt+F4`. The possibilities are:

 1. Adding a confirmation dialog on Exit
 1. Removing exit on ESC all together, users would have to trigger the menu and exit by navigating
 1. Mapping exit to Q instead of ESC

We have to take into consideration that I may add a menu-less mode in Ludo one day, where we can bake the emulator and the ROM into the frontend to have a standalone port of the ROM. So option 1 and 2 are not ideal.

**Comment by NovaPhoenix** [comment]
I like the idea of remapping it to Q, but here's an alternative: What do you think of having users double-tap escape to exit? Granted, this could cause confusion to new users, but it's probably less confusing than quitting right away. Perhaps remapping to Q would be a better option, but I'll throw it out here anyway.

**Comment by kivutar** [comment]
I just noticed that Q was already mapped to `DeviceIDJoypadL`. So we can't use Q.

I'm not a fan of implementing a double pressing logic just for this specific use case.

Implementing a dialog is also a lot of work, but at least it's reusable in a lots of situations, so I'm going to explore this, unless somebody has a better idea.

**Comment by kivutar** [comment]
Please take a look at the pull request. It will display something like this if you try to quit/shutdown/reboot while a game is running:

<img width="1072" alt="Screen Shot 2019-06-09 at 9 16 26 PM" src="https://user-images.githubusercontent.com/442722/59160121-a10ebc80-8afc-11e9-9c77-5a74c0b9b57c.png">

**Comment by NovaPhoenix** [comment]
Looks good to me!

**Comment by kivutar** [comment]
OK thanks. I will try to style it more like a dialog, and maybe use transparency for the background, as it looks too much like a red screen of death now.

**Comment by kivutar** [comment]
Made it look a bit better. Now it's the code that is ugly. I will need to add a widget packing layer.

<img width="1072" alt="Screen Shot 2019-06-10 at 11 24 45 PM" src="https://user-images.githubusercontent.com/442722/59210188-2ff00780-8bd7-11e9-83e3-ad8e31e27184.png">
