### ISSUE TITLE
Feature Request: Box Art Screenshot select in Settings Menu

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#229]
I love the screenshots although I do miss the box art. May I suggest adding an option in settings menu to set the thumbnail to box art or screenshot.

**Comment by kivutar** [comment]
For now I've chosen this screenshot approach because Box Art is more complex than it seems.

1) they are a lot heavier
2) they vary a lot in aspect ratio (some Japanese SNES games have vertical box art)
3) a lots of systems like arcade and game engines simply don't have box arts

Also, I plan to have:

- the currently running game display its image in place of the thumbnail
- ah history list of savestates to quickly resume previous sessions

And for those two features, keeping screenshots would ensure that the look is consistent.

**Comment by johnnyq** [comment]
Got ya thats makes sense
