### ISSUE TITLE
Question/Help on Pull Request to "remember where you are at in the list"

### ISSUE THREAD

**Issue by davidrenne** [libretro/ludo#257]
I want to possibly provide some code so that if I am in a game and I go to the menu and accidentally go back to the main emulator screen or game list, I want it to remember where I was at in the list on the game that is currently playing.

Is that something that a noob to your source code, but an experienced golang developer might be able to whip up?  Any pointers of where to look and modify would be helpful.

I just want the user experience to be smooth in this situation where you press back on accident and have to navigate back to the game and enter it to get your normal save state features that you get when you first press P or Menu.

**Comment by kivutar** [comment]
Hi, it would be difficult to implement, because the menu is stack based, and when you hit cancel, the scene is popped from the stack. So you wouldn't have a good place to store this value in the menu state.

However I agree with you that having to navigate to find the quick menu is bad menu design. Ideally, I'd like to redesign the menu so that the currently running game is shown in an Activity Bubble on top of the UI. And give quick access to coming back to the game (and its contextual menu) from anywhere.

We need to study how traditional consoles solved this issue, and see what can be adapted. The challenge is to find consistent transition animations to go from:
 - playlist entry -> launching the game
 - playlist entry <-> quick menu of a running game
 - history entry -> launching the game
 - history entry <-> quick menu of a running game
 - anywhere <-> quick menu of a running game

But since none of these consoles allows you owning 10k+ games, I suppose we'll have to find our own way of presenting things.

**Comment by davidrenne** [comment]
Arcade allows for 10K games I am sure with all the clones etc.

What if when in a game, you have a close game option and it forces the user to stay in the "in game menu" which has save state etc.  

Because once you go back once to the game list, it is confusing to click OK on a game to get back to that menu, even though it currently keeps you at the selected game you are in at first.

By not allowing the user to even see the games list when in a game, it keeps them in the most important area where they either save the state of the game and close it, or must close it to get back to the main games list.

Overall I dont see why it is important to navigate to other games while you are currently playing a game to launch a new one.  I'd rather always see the normal in game menu when a game is playing and have to close out of the game, rather than the back button showing the list of games.  Because once you are in the list of games its very confusing to click OK on the game to get back to the main in game menu.

Finally, I had a question, is there a way to favorite games?  I saw a favorites count of zero but couldnt find a way to favorite something.  I'll close this issue after a response.

**Comment by kivutar** [comment]
> Overall I dont see why it is important to navigate to other games while you are currently playing a game to launch a new one.
It's not really important, but it's important to be able to navigate to Settings to adjust volume and shader.

Settings could also be made accessible from anywhere from a shortcut. Then once again we need to think of an animation for settings to appear.

> Finally, I had a question, is there a way to favorite games? I saw a favorites count of zero but couldnt find a way to favorite something. I'll close this issue after a response.

Not yet, but it's something that I'd like to add.
