### ISSUE TITLE
Feature Request: Remove show hidden files option

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#261]
to further simplify the settings menu show hidden files option could just be removed. Theres really no need to show hidden files in add games anyway, at least i cant think of a reason.

**Comment by kivutar** [comment]
@RobLoach What do you think? Is there a use case?

**Comment by johnnyq** [comment]
@RobLoach Is this a good choice? I can't really see any reason to show hidden files for scanning games unless some odd case scenario where someone wants to place their roms in a hidden directory, and if that's the case then they should use retroarch

**Comment by RobLoach** [comment]
The original behavior was to always show hidden files. I added the option so that we could hide them.

I've found showing hidden files helpful when configuring the directories. I've often set `~/.config/retroarch/system` as the System Directory, for example. We could always hide them by default in "Add games", and show them in the config directory settings.

**Comment by kivutar** [comment]
Ah you're right, this option is needed.
