### ISSUE TITLE
Add Games: Possibly move to Settings and initiate the directory in /storage/roms instead of /storage 

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#360]
Possibly move to Settings and initiate the directory in /storage/roms instead of /storage.
I was thinking this should be added to settings as this is not used very much just initially to add games.

**Comment by kivutar** [comment]
The directory is initiated in `~`, which happen to be `/storage/` in LudOS, but other things in Linux, Windows and OSX.
We can't assume that people have a `rom` directory present in their home.

The idea of having it in the tab list is because it will add tabs, so it is located is its context.

Settings are built dynamically from the settings struct that is also linked to the settings.toml structure. If we move Add Games to settings, it will create problems when saving the toml.

**Comment by johnnyq** [comment]
That all makes sense. Ill go ahead and close this. Thanks for explaining =]
