### ISSUE TITLE
Console Naming Consistency

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#364]
I have the following below consoles on my Ludo and noticed the gaming console naming convention, would it make sense to rename it to the following

- NES / Famicom - Rename to Nintendo
- Super Nintendo - Keep it the same name
- Mega Drive / Genesis - Rename it to Sega Genesis

**Comment by kivutar** [comment]
Sorry but this topic is too subjective. Depending on the country the user lives in, `Genesis` means nothing to French users. `Nintendo` might not be precise enough to Japanese users.

Right names to use are the one from No-Intro, but they are too long, exactly because they take care of all the cultural differences.

We've shorten the names while trying to keep the widest cultural coverage.

**Comment by johnnyq** [comment]
@kivutar I agree
