### ISSUE TITLE
[Genesis Plus GX] "Disc control" option is enabled on cartridge-based games. And will crash Ludo when you select it.

### ISSUE THREAD

**Issue by fmaida** [libretro/ludo#437]
I'm testing this behaviour with Ludo v0.14.6-altui on a MacBook Air with macOS 11.4

I noticed that under Ludo every game emulated by Genesis Plus GX have an option to swap and replace the CD inserted in the emulated machine.  

This is fine for Sega Mega-CD / Sega CD but not so fine for the other cartridge-based console such as the Sega SG-1000, Sega Master System, Sega Game Gear and Sega Genesis.

![disc-control-on-sg-1000](https://user-images.githubusercontent.com/605017/122634963-74c1a980-d0e1-11eb-9a36-dac3683c3def.png)

Unfortunately, when you try to select "Disc control" on a game console that doesn't support CD-ROM games, Ludo crashes.

These are three log files that I took from three different games for SG-1000, Master System and Genesis:

[sg-1000-bank-panic.log](https://github.com/libretro/ludo/files/6680214/sg-1000-bank-panic.log)
[sms-alex-kidd-miracle-world.log](https://github.com/libretro/ludo/files/6680215/sms-alex-kidd-miracle-world.log)
[genesis-altered-beasts.log](https://github.com/libretro/ludo/files/6680217/genesis-altered-beasts.log)

**Comment by johnnyq** [comment]
It an upstream issue hopefully will be resolved soon

**Comment by fmaida** [comment]
> It an upstream issue hopefully will be resolved soon

I just got a reply on that issue. They told me that a fix might be hard to implement and that the best thing to do is to avoid clicking on that option. So I fear it will be probably end in a WONTFIX tag.

The main problem IMHO is that Ludo crashes each time you select it, either by choice or by mistake.
I'm so sorry for asking you to do more work on Ludo, but IMHO if Genesis-Plus-GX won't be fixed for this I thing you should add this to your todo list and implement some checks to avoid crashes on your own.

**Comment by kivutar** [comment]
I have too look into ways to have go recover crashes that come from C.

**Comment by ekeeke** [comment]
FYI, there are already safeguards implemented in the core C code (libretro.c) to return an error status (false) in case disc control functions are called when emulating non-disc content so the crash likely does not occur in the core itself but in the frontend, probably because it does not check the status returned by the core before proceeding further with its own disc control code. Retroarch, for example, will detect the returned error and display an error message to indicate to end-user this was an invalid command request, but does not crash.

As for the disc control menu appearing whatever the kind of content loaded, as explained in initial issue report, this is a design issue that *might* be fixable with simple changes in the core (libretro.c) but only if libretro frontends design allows setting or clearing disc control environment when new content is loaded (in retro_load_game function) and emulated hardware is detected by the core. The libretro API is not clear about when this environment should be set and if it can be cleared after being set, so there are big chances that the behavior is undefined and frontend-specific (afaik, all cores that use this environment are setting it once for all in retro_init function).

**Comment by kivutar** [comment]
Oh thanks for the info.
I'll handle this frontend side then.
